dashboard:
  password: "admin123"
  
study:
  max_responses_per_pair: 15
  reservation_timeout_minutes: 5
  comparison_question: "Is there a semantic change between the two images?"

prices:
  - ğŸ‘¨â€ğŸ³ğŸ‘¨â€ğŸ³ Et faig un pastis de formatge amb lotus ğŸ°ğŸ° I will make a lotus cheesecake for you ğŸ°ğŸ°
  - ğŸºğŸº Et regalo les meves 3 cerveses preferides ğŸºğŸº I will give you my 3 favorite beers ğŸºğŸº
  - ğŸ‘¨â€ğŸ³ğŸ‘¨â€ğŸ³ Et cuino el millor sandwich que pots dinar a la uni ğŸ”ğŸ” I will make the best sandwich you can eat at uni ğŸ”ğŸ”

points_gamble:
  - 10
  - -10
  - 3
  - -3